### ISSUE TITLE
バグ

### ISSUE THREAD

**Issue by HirohitoSuzuki** [HirohitoSuzuki/git-empit-training-201906#1]
## 操作手順
* 〜したら
* 〜になった

## 本来の想定
* 〜したら
* 〜になってほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by HirohitoSuzuki** [comment]
マイナス値が入力できない

**Comment by KogawaShota** [comment]
割り算の結果が掛け算になる

**Comment by KogawaShota** [comment]
小数点の四捨五入のミス

**Comment by HirohitoSuzuki** [comment]
> ## 操作手順
> * 〜したら
> * 〜になった
> 
> ## 本来の想定
> * 〜したら
> * 〜になってほしい
> 
> ## 操作環境
> * OS
> * OSバージョン
> * ブラウザ
> * ブラウザバージョン
